//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNotepad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UnsavedTime {
            get {
                return ((bool)(this["UnsavedTime"]));
            }
            set {
                this["UnsavedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int UnsavedTimeInterval {
            get {
                return ((int)(this["UnsavedTimeInterval"]));
            }
            set {
                this["UnsavedTimeInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int DefaultUnsavedTimeInterval {
            get {
                return ((int)(this["DefaultUnsavedTimeInterval"]));
            }
            set {
                this["DefaultUnsavedTimeInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UTF-8")]
        public string DefaultEncoding {
            get {
                return ((string)(this["DefaultEncoding"]));
            }
            set {
                this["DefaultEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
  <string>name|Exprimental Item;path|C:\</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PinnedDocuments {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PinnedDocuments"]));
            }
            set {
                this["PinnedDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WordWrapEnabled {
            get {
                return ((bool)(this["WordWrapEnabled"]));
            }
            set {
                this["WordWrapEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("english")]
        public string CurrentLanguage {
            get {
                return ((string)(this["CurrentLanguage"]));
            }
            set {
                this["CurrentLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveChangesWhenExiting {
            get {
                return ((bool)(this["SaveChangesWhenExiting"]));
            }
            set {
                this["SaveChangesWhenExiting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dpaulootavio5.000webhostapp.com/Taiyou/taiyou_app/tnotepad/")]
        public string WebserviceURL {
            get {
                return ((string)(this["WebserviceURL"]));
            }
            set {
                this["WebserviceURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindowShadow {
            get {
                return ((bool)(this["WindowShadow"]));
            }
            set {
                this["WindowShadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmoothVisualElements {
            get {
                return ((bool)(this["SmoothVisualElements"]));
            }
            set {
                this["SmoothVisualElements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StrechWindowContentsWhenResizing {
            get {
                return ((bool)(this["StrechWindowContentsWhenResizing"]));
            }
            set {
                this["StrechWindowContentsWhenResizing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TaiyouDark")]
        public string CurrentTheme {
            get {
                return ((string)(this["CurrentTheme"]));
            }
            set {
                this["CurrentTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ForceDoubleBuffer {
            get {
                return ((bool)(this["ForceDoubleBuffer"]));
            }
            set {
                this["ForceDoubleBuffer"] = value;
            }
        }
    }
}
